some fixes and changes

diff --git a/.github/workflows/distribution-build.yml b/.github/workflows/distribution-build.yml
--- a/.github/workflows/distribution-build.yml
+++ b/.github/workflows/distribution-build.yml
@@ -1,16 +1,24 @@
 name: Build Yocto Image
 
 on:
+  #push:
+  #  branches:
+  #    - main
+  #pull_request:
+  #  branches:
+  #    - main
   workflow_dispatch:
     inputs:
       trigger:
         description: "start manually"
         required: true
         default: "yes"
+  #schedule:
+  #  - cron: '0 2 * * 0'  # jeden Sonntag um 02:00 Uhr nachts  
 
 jobs:
   build:
-    runs-on: self-hosted
+    runs-on: [self-hosted, pqbox-runner]
     env:
       ORGANISATION_NAME: "emblincram"
       CONTAINER_NAME: "devcon"
@@ -21,89 +29,80 @@ jobs:
       packages: read
 
     steps:
+      - name: Log in to GitHub Container Registry
+        run: |
+          echo "$GHCR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+      - name: Prepare Workspace
+        run: |
+          # todo: set proper user
+          # move cache and downloads 
+          docker run --rm \
+            -v ${{ runner.workspace }}/../:/mnt \
+            ghcr.io/$ORGANISATION_NAME/$CONTAINER_NAME-clean:latest /bin/bash -i -c "
+              mkdir -p /mnt/sstate-cache /mnt/downloads
+
+              #mv /mnt/${{ github.event.repository.name }}/sstate-cache/* /mnt/sstate-cache/ || true
+              #mv /mnt/${{ github.event.repository.name }}/downloads/* /mnt/downloads/ || true
+
+              chmod -R a+rw /mnt/sstate-cache /mnt/downloads
+            "
+
+          # cleanup workspace
+          docker run --rm \
+            -v ${{ runner.workspace }}/:/mnt \
+            ghcr.io/$ORGANISATION_NAME/$CONTAINER_NAME-clean:latest /bin/bash -i -c "
+              rm -rf /mnt/*
+              mkdir -p /mnt/${{ github.event.repository.name }} /mnt/logs /mnt/build
+              chmod -R 777 /mnt
+            "
+
       - name: Checkout Repository
         uses: actions/checkout@v4
         with:
           submodules: true
-          clean: false
-          path: "yocto-src-${{ github.run_id }}"  # Neuer, eindeutiger Ordner
-
-      - name: Set Working Directory
-        run: |
-          echo "Using fresh Yocto source at: yocto-src-${{ github.run_id }}"
-          ln -sfn ${{ runner.workspace }}/yocto-src-${{ github.run_id }} ${{ runner.workspace }}/meta-pq-box
-
-      - name: Log in to GitHub Container Registry
-        run: |
-          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
-
-      - name: Pull Yocto DevContainer Image
-        run: |
-          docker pull ghcr.io/$ORGANISATION_NAME/$CONTAINER_NAME:latest
-
-      - name: Run Install Script
-        run: |          
-          cd ${{ github.workspace }}
-          if [ ! -f install.sh ]; then
-            echo "Error: install.sh not found!"
-            exit 1
-          fi
-          chmod +x install.sh
-          GHCR_PAT=${{ secrets.GHCR_PAT }} ./install.sh
-          cd ..
-
-      - name: Run initialize-command.sh
-        run: |
-          cd ${{ runner.workspace }}
-          if [ ! -f $LAYER_NAME/toolbox/initialize-command.sh ]; then
-            echo "Error: initialize-command.sh not found!"
-            exit 1
-          fi
-          chmod +x $LAYER_NAME/toolbox/initialize-command.sh
-          ./$LAYER_NAME/toolbox/initialize-command.sh .
+          clean: true
 
       - name: Run Yocto Build
         run: |
-          cd ${{ runner.workspace }}
-          docker run --rm \
-            -v ${{ runner.workspace }}/application:/home/yocto/app \
-            -v ${{ runner.workspace }}/build:/home/yocto/build \
-            -v ${{ runner.workspace }}/meta-arm:/home/yocto/meta-arm \
-            -v ${{ runner.workspace }}/meta-ti:/home/yocto/meta-ti \
-            -v ${{ runner.workspace }}/meta-openembedded:/home/yocto/meta-openembedded \
-            -v ${{ runner.workspace }}/$LAYER_NAME:/home/yocto/$LAYER_NAME \
-            -v ${{ runner.workspace }}/poky:/home/yocto/poky \
-            -v ${{ runner.workspace }}/sstate-cache:/home/yocto/sstate-cache \
-            -v ${{ runner.workspace }}/downloads:/home/yocto/downloads \
-            -w /home/yocto \
-            --user yocto \
-            ghcr.io/$ORGANISATION_NAME/$CONTAINER_NAME:latest /bin/bash -i -c "
-              mkdir -p ~/.ssh
-              echo '${{ secrets.SSH_KEY }}' > ~/.ssh/id_rsa
-              chmod 600 ~/.ssh/id_rsa
-              mkdir -p /home/yocto/downloads
-              mkdir -p /home/yocto/sstate-cache
-              sshfs -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST}:/home/rko/work/downloads /home/yocto/downloads
-              sshfs -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST}:/home/rko/work/sstate-cache /home/yocto/sstate-cache
-              echo 'YOCTO_SSTATE_DIR=/home/yocto/sstate-cache' >> /etc/environment
-              echo 'YOCTO_DL_DIR=/home/yocto/downloads' >> /etc/environment
-              source /etc/environment    
-              chown -R yocto:yocto /home/yocto
-              chmod +x $LAYER_NAME/toolbox/post-create-command.sh
-              ./$LAYER_NAME/toolbox/post-create-command.sh /home/yocto
-              source activate-env.sh
-              bitbake core-image-full-cmdline 2>&1 | tee build-log.txt
-              fusermount -u /home/yocto/sstate-cache || true
-              fusermount -u /home/yocto/downloads || true
-            "
-        env:
-          SSH_USER: ${{ secrets.SSH_USER }}
-          SSH_HOST: ${{ secrets.SSH_HOST }}
-          SSH_KEY: ${{ secrets.SSH_KEY }}
+          cd ${{ github.workspace }}
+          set -eo pipefail
 
+          docker run --rm \
+            -v ${{ github.workspace }}:/home/yocto \
+            -v ${{ runner.workspace }}/../sstate-cache:/home/yocto/sstate-cache \
+            -v ${{ runner.workspace }}/../downloads:/home/yocto/downloads \
+            -v ${{ runner.workspace }}/logs:/home/yocto/logs \
+            -w /home/yocto \
+            --user "$(id -u):$(id -g)" \
+            --env GITHUB_TOKEN=$GHCR_PAT \
+            --env YOCTO_SSTATE_DIR=/home/yocto/sstate-cache \
+            --env YOCTO_DL_DIR=/home/yocto/downloads \
+            --env YOCTO_LOGS_DIR=/home/yocto/logs \
+            ghcr.io/$ORGANISATION_NAME/$CONTAINER_NAME-min:latest /bin/bash -i -c "
+              cd .scripts || { echo 'ERROR: Konnte nicht in .scripts wechseln'; exit 1; }
+              chmod +x post-create-command.sh
+              ./post-create-command.sh /home/yocto/ || { echo 'ERROR: Skript konnte nicht ausgeführt werden'; exit 1; }
+              cd ..
+
+              [ -f .scripts/activate-env.sh ] && cp .scripts/activate-env.sh . || echo 'Error: .scripts/activate-env.sh fehlt'
+              chmod +x activate-env.sh
+
+              . activate-env.sh || echo 'Error: activate-env.sh konnte nicht ausgeführt werden'
+
+              TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
+              bitbake core-image-full-cmdline 2>&1 | tee /home/yocto/logs/build-log_$TIMESTAMP.txt
+            "
+      - name: Upload Logs
+        uses: actions/upload-artifact@v4
+        with:
+          name: yocto-build-logs
+          path: ${{ runner.workspace }}/logs/build-log_*.txt
+          retention-days: 14
+    
       - name: Upload Build Artifact
         uses: actions/upload-artifact@v4
         with:
           name: yocto-image
           path: ${{ runner.workspace }}/build/deploy-ti/images/beagle-x15/core-image-full-cmdline-*.wic*
-          retention-days: 7
+          retention-days: 14
